In [10]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Quantstream Data I/O Demonstration

This notebook demonstrates how to use the Quantstream API to read data from Financial Modeling Prep. We will go over basic usage of the API by pulling and displaying data for a few stocks. In this example, we will pull the historical stock prices for Apple, Microsoft, and Tesla. 

The Quantstream API is a simple and easy-to-use API that provides access to a wide range of financial data. The API is designed to be user-friendly and intuitive, making it easy for data scientists and developers to access the data they need.

In [11]:
import quantstream as qs
import os
import xarray as xr
import warnings

warnings.filterwarnings("ignore")

### The API Key

To use the Quantstream API to pull data from financial modeling prep, you will need an API key. You can get a free API key by signing up at [Financial Modeling Prep](https://financialmodelingprep.com/developer/docs/pricing).

For this demonstration, we will use a Quantstream's ability to read an API key from an environment variable. You can set the environment variable `FMP_API_KEY` to your API key to use it in this notebook.

In [20]:
ds_daily = qs.timeseries.get_daily(
    symbol="AAPL",
    from_date="2024-10-01",
    to_date="2024-10-10",
)
ds_daily.to_dataframe()

,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
time,,,,,,,,,,,,
2024-10-10,227.78,229.50,227.17,229.04,228.79,28183544,28183544,1.26,0.55317,228.3725,"October 10, 24",0.005532
2024-10-09,225.23,229.75,224.83,229.54,229.29,33591100,33591100,4.31,1.91000,227.3375,"October 09, 24",0.019100
2024-10-08,224.30,225.98,223.25,225.77,225.52,31855700,31855700,1.47,0.65537,224.8250,"October 08, 24",0.006554
2024-10-07,224.50,225.69,221.33,221.69,221.45,39505400,39505400,-2.81,-1.25000,223.3025,"October 07, 24",-0.012500
2024-10-04,227.90,228.00,224.13,226.80,226.55,37345098,37345098,-1.10,-0.48267,226.7075,"October 04, 24",-0.004827
2024-10-03,225.14,226.81,223.32,225.67,225.42,34044200,34044200,0.53,0.23541,225.2350,"October 03, 24",0.002354
2024-10-02,225.89,227.37,223.02,226.78,226.53,32880605,32880605,0.89,0.39400,225.7650,"October 02, 24",0.003940
2024-10-01,229.52,229.65,223.74,226.21,225.96,63285048,63285048,-3.31,-1.44000,227.2800,"October 01, 24",-0.014400

In the example above we assume that the API key is stored in the environment variable `FMP_API_KEY`. If you have not set the environment variable, you can set it in the notebook by running the following code:

In [13]:
fmp_api_key = os.environ["FMP_API_KEY"]

In [14]:
qs.set_fmp_api_key(api_key=fmp_api_key)

In [15]:
qs.show_api_keys()

{'fmp': 'N8D8Ww66GenGwDjVVky0ioWWlJMboblF'}

As you can see, the Quantstream API will store the API key in a global variable and use it to authenticate requests to the API. This way, you only need to set the API key once, and it will be used for all subsequent requests.

In [23]:
ds_intra = qs.timeseries.get_intraday(
    symbol="AAPL",
    time_delta="1min",
    from_date="2024-11-15",
    to_date="2024-11-17",
)
ds_intra.to_dataframe()

                       open     low    high   close   volume
time
2024-11-15 15:59:00  225.13  224.86  225.23  224.92   753859
2024-11-15 15:58:00  225.09  224.98  225.16  225.13   307314
2024-11-15 15:57:00  225.03  225.00  225.18  225.09   179925
2024-11-15 15:56:00  225.19  224.95  225.19  225.03   213244
2024-11-15 15:55:00  225.14  224.86  225.21  225.20   311056
...                     ...     ...     ...     ...      ...
2024-11-15 09:34:00  226.26  226.18  226.60  226.34   116920
2024-11-15 09:33:00  226.21  226.16  226.60  226.26   159688
2024-11-15 09:32:00  226.57  226.06  226.57  226.22   162716
2024-11-15 09:31:00  226.61  226.32  226.92  226.57   152693
2024-11-15 09:30:00  226.40  225.86  226.83  226.61  3793586

[390 rows x 5 columns]

### Visualizing Time Series Data

Quantstream provides a simple interface for working with time series data. You can use the `plot_candlestick` method to visualize historical stock prices as candlestick charts. This method takes a pandas DataFrame with OHLC (Open, High, Low, Close) data and plots a candlestick chart.

In [17]:
ds_daily.plot_candlestick()

In [18]:
ds_intra.plot_candlestick()